<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>DynamicFinancialSystem</AssemblyName>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GamePath>D:\steam\steamapps\common\Stardew Valley</GamePath>
    <EnableModDeploy>true</EnableModDeploy>
    <EnableModZip>true</EnableModZip>
    <ModFolderName>DynamicFinancialSystem</ModFolderName>
    <ModDllName>DynamicFinancialSystem.dll</ModDllName>
    <DefaultItemExcludes>$(DefaultItemExcludes);Tests\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(GamePath)\smapi-internal\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
